CREATE TABLE IF NOT EXISTS errors (
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    message VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);